#!/usr/bin/env python3
"""Export every archived EAQECC witness (and closed-form family members)
as a Magma-loadable data file for independent re-verification.

Each record is  <q, n, k_claim, d_claim, c_claim, L_basis, tag>  where
L_basis lists the generators of L = S^perp over F_q, encoded as integers
(prime q: the field element itself; q=4: 0,1,2,3 = 0,1,w,w+1).

Magma is then asked to re-derive k, c and d from scratch — see
scripts/verify_eaqecc.magma.
"""

import glob
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE / "alphaevolve_eaqecc"))

import helpers_eaqecc as H2  # noqa: E402  (qubit, bit-packed)
from helpers_eaqecc_fq import Fq, vecq  # noqa: E402

W = ROOT / "artifacts" / "witnesses"
# The archived run (artifacts/magma/eaqecc_data.m + log) predates this
# layout and omitted the q=3 witnesses. A fresh export goes to pending/ so
# the archived data file keeps matching the archived log until Magma has
# been re-run on the new export; then move both into artifacts/magma/.
OUT = ROOT / "artifacts" / "magma" / "pending" / "eaqecc_data.m"
recs = []


def add(q, n, k, d, c, basis, tag):
    recs.append({"q": q, "n": n, "k": k, "d": d, "c": c,
                 "L": [[int(x) for x in row] for row in basis], "tag": tag})


# ---- qubit: archived stabilizer sets -> L = S^perp (bit-packed ints) -------
for p in sorted(glob.glob(str(W / "q2" / "SOLUTION_*.json"))):
    s = json.load(open(p))
    t = s["target"]
    n = t["n"]
    L = H2.nullspace([H2._J(int(g), n) for g in s["generators"]], 2 * n)
    basis = [[(int(v) >> b) & 1 for b in range(2 * n)] for v in L]
    add(2, n, t["k"], t["d"], t["c"], basis, Path(p).stem)

# ---- qutrit / q=4 / q=5 witnesses (L basis stored directly) ---------------
for pat, q in ((W / "q3" / "SOLUTION3_*.json", 3),
               (W / "q4" / "SOLUTION4_*.json", 4),
               (W / "q5" / "SOLUTION5_*.json", 5)):
    for p in sorted(glob.glob(str(pat))):
        s = json.load(open(p))
        t = s["target"]
        add(q, t["n"], t["k"], t["d"], t["c"], s["L_basis"], Path(p).stem)


# ---- closed-form family members (the theorems themselves) ----------------
def unified(F, n):
    """Unified family L basis: q Z-pairs + (a = X^n, b)."""
    q = F.q
    neg1 = int(F.NEG[1])
    rows = []
    for i in range(q):
        p = [(0, 0)] * n
        p[2 * i], p[2 * i + 1] = (0, 1), (0, neg1)
        rows.append(vecq(p, n))
    a = vecq([(1, 0)] * n, n)
    z2 = 0 if q in (2, 4) else 1
    bp = []
    for i in range(q):
        bp += [(i, 1), (i, z2)]
    bp += [(0, 1)] * (n - 2 * q)
    b = vecq(bp, n)
    if F.sform(a, b, n) == 0:
        for val in range(2, q):
            bp2 = list(bp)
            bp2[-1] = (0, val)
            b2 = vecq(bp2, n)
            if F.sform(a, b2, n) != 0:
                b = b2
                break
        else:
            return None
    return rows + [a, b]


for q in (2, 3, 4, 5):
    F = Fq(q)
    for n in range(2 * q + 1, 2 * q + 7):
        L = unified(F, n)
        if L is None:
            continue
        add(q, n, 1, n - 1, n - q - 1, L, f"unified_q{q}_n{n}")

# qutrit table family (the 25-gap theorem)
F3 = Fq(3)
for n in range(5, 17):
    rows = [vecq([(0, 1), (0, 2)] + [(0, 0)] * (n - 2), n),
            vecq([(0, 0)] * 2 + [(0, 1), (0, 2)] + [(0, 0)] * (n - 4), n)]
    a = vecq([(1, 0)] * n, n)
    tail = [(0, 1)] * (n - 4)
    if n % 3 == 0:
        tail[-1] = (0, 2)
    b = vecq([(1, 1), (1, 1), (2, 1), (2, 1)] + tail, n)
    add(3, n, 1, n - 1, n - 3, rows + [a, b], f"qutrit_table_family_n{n}")

out = ["// auto-generated by scripts/export_for_magma.py — do not edit",
       "DATA := ["]
for i, r in enumerate(recs):
    L = ", ".join("[" + ",".join(str(x) for x in row) + "]" for row in r["L"])
    out.append(f'  <{r["q"]}, {r["n"]}, {r["k"]}, {r["d"]}, {r["c"]}, '
               f'[{L}], "{r["tag"]}">{"," if i + 1 < len(recs) else ""}')
out.append("];")
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(out) + "\n")
print(f"exported {len(recs)} codes -> {OUT.relative_to(ROOT)}")
print("next: magma -b", OUT.relative_to(ROOT), "scripts/verify_eaqecc.magma "
      "> artifacts/magma/pending/magma_verification.log")
from collections import Counter
print("by q:", dict(Counter(r["q"] for r in recs)))
