"""Typeset structured task summaries as native text and export matching SVGs.

The archived task specifications are not modified. Main-paper text uses the
generated TeX directly, without a figure float, image scaling or caption.
Standalone PDF/SVG/PNG exports provide the same document layout for inspection.
"""
from pathlib import Path
import shutil
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
PAPER = ROOT / 'paper/iclr2027/paper'
OUT = ROOT / 'paper/iclr2027/task_specs'

STYLE = r'''% Generated by scripts/make_task_spec_panels.py.
\newcommand{\taskheading}[2]{%
  \par\addvspace{8pt}\noindent
  {\small\rmfamily\bfseries\color{achieve}#1}\hfill
  {\footnotesize\rmfamily\color{black!60}#2}%
  \par\nobreak\vspace{3pt}{\color{achieve!45}\hrule height .5pt}%
  \nobreak\vspace{4pt}}
\newcommand{\taskrow}[3]{%
  \begin{tcolorbox}[enhanced,colback=#1,frame hidden,boxrule=0pt,
    arc=0pt,left=6pt,right=6pt,top=3pt,bottom=3pt,
    before skip=0pt,after skip=2pt]
  \small\rmfamily
  \begin{tabularx}{\linewidth}{@{}>{\raggedright\arraybackslash\hyphenpenalty=10000\exhyphenpenalty=10000}p{2.55cm}@{\hspace{8pt}}X@{}}
  {\footnotesize\rmfamily\bfseries\color{black!65}#2} & #3
  \end{tabularx}
  \end{tcolorbox}}
\newcommand{\tasksource}[1]{%
  \par\nobreak\noindent{\scriptsize\rmfamily\color{black!55}#1}\par}
'''

PANELS = [
    ('initial', 'Discovery campaigns 1--2', 'Initial search', [
        ('achieve!10', 'Researcher proposal',
         r'Explore cyclic qubit shifts, constructive warm starts, $\mathrm{GF}(4)$-additive constructions and coupled generator moves. Reuse structure between targets sharing $(n,c)$.'),
        ('white', 'Task to the model',
         r'Construct binary EAQECCs for 68 open table entries. Each target $[[n,k,d;c]]_2$ has listed lower distance bound $d-1$ and upper bound $d$.'),
        ('white', 'Exact feedback',
         r'Match the requested $(k,c)$ and reach distance $d$. The evaluator checks the symplectic constraints and reports the number of nontrivial logical operators below the target distance.'),
        ('white', 'Knowledge supplied',
         r'Stabilizer representation, evaluator access and construction directions. The family formula derived later was not supplied.'),
    ], 'Source: archived task specifications for campaigns 1 and 2.'),
    ('updated', 'Discovery campaigns 3--4', 'After generalization', [
        ('achieve!10', 'Researcher result',
         r'The recorded qubit constructions $[[7,1,6;4]]_2$, $[[9,1,8;6]]_2$ and $[[11,1,10;8]]_2$ were generalized by researchers to the odd-length family $[[n,1,n-1;n-3]]_2$.'),
        ('achieve!10', 'Researcher proposal',
         r'Develop further constructions using other shift steps, quasi-cyclic orbits, multiple radical blocks, $\mathrm{GF}(4)$-additive constructions, and extension, shortening or puncturing of the known family.'),
        ('white', 'Task to the model',
         r'Search 329 qubit parameter targets with $5\le n\le13$, including listed gaps and previously unlisted parameter cells. The task now explicitly includes the discovered qubit family.'),
        ('white', 'Exact feedback',
         r'Use the same parameter and distance checks. The specification also permits constructing the smaller dual space and converting it to stabilizer generators for evaluation.'),
    ], 'Source: archived task specifications for campaigns 3 and 4.'),
    ('controlled', 'Controlled study', 'Shared proposal for both policies', [
        ('achieve!10', 'Researcher proposal',
         r'Maintain and mutate a basis of $L=S^\perp$ throughout search. Convert each candidate $L$ to $S$ for exact evaluation. For the training targets, $L$ has only four basis vectors.'),
        ('white', 'Task to the model',
         r'Implement \texttt{search(target, max\_evals)} under a separate quota for each target and seed. Independent proposals and iterative evolution receive the same research suggestion.'),
        ('white', 'Information withheld',
         r'No successful code matrix, family formula or working $L$-side search program is supplied. There is no controller-provided initialization.'),
    ], 'Source: archived controlled-study task; this is separate from the discovery campaigns.'),
]

PREAMBLE = r'''\documentclass[border=2pt]{standalone}
\usepackage[T1]{fontenc}
\usepackage{times,amsmath,amssymb,xcolor,tabularx}
\usepackage[most]{tcolorbox}
\definecolor{achieve}{RGB}{31,119,120}
'''


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    (PAPER / 'task_spec_style.tex').write_text(STYLE)
    for slug, title, subtitle, rows, source in PANELS:
        body = f'\\taskheading{{{title}}}{{{subtitle}}}\n'
        for color, role, content in rows:
            body += f'\\taskrow{{{color}}}{{{role}}}{{{content}}}\n'
        body += f'\\tasksource{{{source}}}\n'
        body = '\\begin{minipage}{\\linewidth}\n' + body + '\\end{minipage}\n\\par\n'
        (PAPER / f'task_spec_{slug}.tex').write_text(body)
        with tempfile.TemporaryDirectory(prefix='eaqecc-task-spec-') as temp:
            temp = Path(temp)
            tex = PREAMBLE + STYLE + '\n\\begin{document}\n\\begin{minipage}{5.5in}\n' + body + '\\end{minipage}\n\\end{document}\n'
            (temp / 'task.tex').write_text(tex)
            proc = subprocess.run(['tectonic', '-X', 'compile', 'task.tex'], cwd=temp,
                                  capture_output=True, text=True)
            if proc.returncode:
                raise RuntimeError(proc.stdout + proc.stderr)
            pdf = OUT / f'{slug}.pdf'
            shutil.copyfile(temp / 'task.pdf', pdf)
            subprocess.run(['pdftocairo', '-svg', str(pdf), str(OUT / f'{slug}.svg')], check=True)
            subprocess.run(['pdftoppm', '-singlefile', '-scale-to', '1800', '-png',
                            str(pdf), str(OUT / slug)], check=True)
        print(f'{slug}: native TeX + PDF/SVG/PNG')


if __name__ == '__main__':
    main()
