#!/usr/bin/env python3
"""Generate the ICLR vector overview, including between-campaign HITL work."""

import argparse
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", type=Path, default=ROOT / "figures")
    parser.add_argument("--standalone", action="store_true",
                        help="also write a standalone TeX document for PDF export")
    args = parser.parse_args()
    args.out_dir.mkdir(parents=True, exist_ok=True)
    logo_dir = args.out_dir / "overview_assets"
    logo_dir.mkdir(exist_ok=True)
    for name in ("python_logo.png", "magma_logo.png", "lean_logo.png"):
        shutil.copyfile(ROOT / "assets/logos" / name, logo_dir / name)
    witness = json.loads((ROOT / "artifacts/witnesses/q2/SOLUTION_n11_k1_c8_d10.json").read_text())
    witness_count = len(list((ROOT / "artifacts/witnesses").glob("q*/SOLUTION*.json")))
    refutations = json.loads((ROOT / "artifacts/refutations/registry.json").read_text())
    assert all(entry["status"].startswith("certified") for entry in refutations)
    cells = []
    # A six-row excerpt of an archived stabilizer support matrix, not invented data.
    for row, generator in enumerate(witness["generators"][:6]):
        for col in range(11):
            color = "ovteal" if (generator >> (2 * col)) & 3 else "ovteal!10"
            cells.append(rf"\fill[{color}] ({7.03 + .112*col:.3f},{3.59-.112*row:.3f}) rectangle ++(.084,-.084);")
    content = r"""% GENERATED by scripts/make_pipeline_overview.py; edit the generator.
\definecolor{ovink}{HTML}{203849}%
\definecolor{ovblue}{HTML}{2C5F8A}%
\definecolor{ovteal}{HTML}{1F7778}%
\definecolor{ovhuman}{HTML}{985B23}%
\definecolor{ovred}{HTML}{A54339}%
\begin{tikzpicture}[x=1cm,y=1cm,>=Latex,
  font=\rmfamily\fontsize{9.2}{10.8}\selectfont,text=ovink,
  flow/.style={->,draw=ovink!85,line width=.95pt},
  humanflow/.style={->,draw=ovhuman,line width=.95pt,dashed},
  small/.style={font=\rmfamily\fontsize{8.2}{9.8}\selectfont},
  label/.style={font=\rmfamily\bfseries\fontsize{9.2}{10.5}\selectfont},
  card/.style={rounded corners=3pt,draw=ovink!40,line width=.75pt,fill=white}]
\path[use as bounding box] (-.03,.24) rectangle (14.03,7.16);

% Researcher analysis and formal checking are separate from the search loop.
\begin{scope}[yshift=.65cm]
\filldraw[rounded corners=4pt,fill=ovhuman!6,draw=ovhuman!40,line width=.65pt]
  (0,5.18) rectangle (9.95,6.48);
\fill[ovhuman!12] (.17,5.34) rectangle (2.75,6.32);
\draw[ovhuman,line width=1pt] (.53,6.00) circle (.10);
\draw[ovhuman,line width=1pt,rounded corners=2pt] (.34,5.62) -- (.34,5.75)
  .. controls (.36,5.92) and (.70,5.92) .. (.72,5.75) -- (.72,5.62);
\node[label,anchor=west,text=ovhuman] at (.88,6.03) {Researcher};
\node[small,anchor=west,text=ovhuman] at (.88,5.63) {in the loop};
\node[label,align=center,text width=3.35cm,inner sep=0pt] at (4.30,6.05)
  {Propose and revise ideas};
\node[small,align=center] at (4.30,5.48) {between campaigns};
\node[label,align=center,text width=3.35cm,inner sep=0pt] at (8.00,6.05)
  {Generalize and prove};
\node[small,align=center] at (8.00,5.48) {from discovered codes};
% The supplied logo is included unchanged. This box denotes a proof-checking stage.
\draw[card,draw=ovteal!65] (10.65,5.18) rectangle (14,6.48);
\node[inner sep=0pt] at (12.325,6.00)
  {\includegraphics[width=1.55cm]{overview_assets/lean_logo.png}};
\node[small,text=ovteal] at (12.325,5.39) {Machine-check proofs};
\draw[flow,ovteal] (9.98,5.83)--(10.62,5.83);
\end{scope}

% Four stages, with visual examples of the objects they operate on.
\foreach \x/\w in {0/2.42,2.97/3.30,6.80/3.08,10.43/3.57}
  \draw[card] (\x,.72) rectangle ++(\w,3.78);
\fill[ovink!6] (.015,3.91) rectangle (2.405,4.48);
\fill[ovblue!9] (2.985,3.91) rectangle (6.255,4.48);
\fill[ovteal!9] (6.815,3.91) rectangle (9.865,4.48);
\fill[ovink!6] (10.445,3.91) rectangle (13.985,4.48);
\node[label,anchor=west] at (.19,4.22) {01\quad TARGET};
\node[label,anchor=west,text=ovblue] at (3.16,4.22) {02\quad EVOLVE};
\node[label,anchor=west,text=ovteal] at (6.99,4.22) {03\quad VERIFY};
\node[label,anchor=west] at (10.62,4.22) {04\quad DISCOVER};

% A miniature reference-table excerpt (the three family targets).
\node[small] at (.62,3.50) {$n$};
\node[small] at (1.59,3.50) {$d_\ell\;\text{--}\;d_u$};
\draw[ovink!30,line width=.45pt] (.26,3.28)--(2.16,3.28);
\foreach \n/\lo/\hi/\y in {7/5/6/3.05,9/7/8/2.65,11/9/10/2.25}{
  \node[small] at (.62,\y) {$\n$};
  \node[small] at (1.59,\y) {$\lo\;\text{--}\;\hi$};
}
\node[small,align=center,text width=2.04cm,inner sep=0pt] at (1.21,1.40)
  {Reference tables\\Known bounds};

% Candidate programs and the actual inner feedback loop.
\draw[rounded corners=2pt,fill=ovblue!5,draw=ovblue!60,line width=.7pt]
  (3.17,3.09) rectangle (5.37,3.82);
\node[small,text=ovblue,align=center,text width=2.10cm,inner sep=0pt]
  at (4.27,3.455) {LLM evolves\\a program};
\foreach \row in {0,1,2}
  \foreach \col in {0,...,7}{
    \pgfmathtruncatemacro{\active}{mod(\col-\row+8,8)}
    \ifnum\active<3
      \fill[ovblue!80] (3.63+.16*\col,2.64-.13*\row) rectangle ++(.12,-.09);
    \else
      \fill[ovblue!10] (3.63+.16*\col,2.64-.13*\row) rectangle ++(.12,-.09);
    \fi
  }
\node[small,text=ovblue] at (4.27,2.05) {Generators};
\draw[rounded corners=2pt,fill=ovteal!6,draw=ovteal!60,line width=.7pt]
  (3.17,.96) rectangle (5.37,1.57);
\node[small,text=ovteal] at (4.27,1.265) {Exact evaluator};
% Keep the arrowhead inside the gap, clear of both the program and grid.
\draw[->,>={Latex[length=1.2mm,width=1mm]},line width=.8pt,ovblue]
  (4.27,3.02)--(4.27,2.73);
\draw[->,>={Latex[length=1mm,width=.9mm]},line width=.75pt,ovblue]
  (4.27,1.82)--(4.27,1.64);
\draw[flow,ovblue] (5.39,1.265)--(6.07,1.265)--(6.07,3.455)--(5.40,3.455);
\node[small,rotate=90,inner sep=0pt,text=ovblue] at (5.82,2.37) {feedback};

% Support pattern of six archived n=11 generators, with independent checks.
__CELLS__
\node[inner sep=0pt] at (9.03,3.62)
  {\includegraphics[width=1.38cm]{overview_assets/python_logo.png}};
\node[inner sep=0pt] at (9.03,3.17)
  {\includegraphics[width=.966cm]{overview_assets/magma_logo.png}};
\node[small,text=ovteal] at (8.34,2.73) {Recompute $k,c,d$};
\draw[ovink!30,line width=.45pt] (7.00,2.50)--(9.68,2.50);
\draw[ovred!75,line width=.75pt] (7.09,1.60)--(7.09,2.27)--(7.57,2.27)
  --(7.71,2.13)--(7.71,1.60)--cycle;
\draw[ovred!75,line width=.65pt] (7.23,2.04)--(7.53,2.04) (7.23,1.88)--(7.53,1.88);
\node[small,align=left,anchor=west,text width=1.73cm,inner sep=0pt]
  at (7.94,1.99) {SAT + DRAT\\proof check};
\node[small,text=ovred,align=center,text width=2.65cm,inner sep=0pt]
  at (8.34,1.16) {Certify nonexistence};

% Bounds meet; an exact code and the sizes of the checked archive.
\node[small,text=ovteal] at (11.13,3.56) {$d_\ell\uparrow$};
\node[small,text=ovred] at (13.25,3.56) {$d_u\downarrow$};
\draw[->,line width=1.1pt,ovteal] (10.92,3.26)--(11.98,3.26);
\draw[->,line width=1.1pt,ovred] (13.49,3.26)--(12.42,3.26);
\draw[ovink,line width=.8pt] (12.20,3.26) circle (.16);
\draw[ovink,line width=.7pt] (12.12,3.26)--(12.18,3.19)--(12.30,3.35);
\node[small] at (12.215,2.87) {Tighten code bounds};
\node[font=\fontsize{10.6}{12}\selectfont] at (12.215,2.38) {$[[11,1,10;8]]_2$};
\node[font=\rmfamily\bfseries\fontsize{15}{17}\selectfont,text=ovteal] at (11.37,1.77) {__WITNESS_COUNT__};
\node[font=\rmfamily\bfseries\fontsize{15}{17}\selectfont,text=ovred] at (13.02,1.77) {__REFUTATION_COUNT__};
\node[small] at (11.37,1.24) {codes};
\node[small] at (13.02,1.24) {exclusions};

% Main construction route and a separate nonexistence route.
\draw[flow] (2.44,3.37)--(2.94,3.37);
\draw[flow,ovteal] (6.29,3.37)--(6.77,3.37);
\draw[flow,ovteal] (9.90,3.37)--(10.40,3.37);
\draw[flow,ovred] (1.21,.70)--(1.21,.27)--(6.52,.27)--(6.52,1.99)--(6.77,1.99);
\node[small,inner sep=1pt,text=ovred] at (3.80,.51) {nonexistence targets};

% Dashed arrows are researcher intervention, separate from automated feedback.
\draw[humanflow] (4.53,5.81)--(4.53,4.54);
\node[small,fill=white,inner sep=2pt,text=ovhuman] at (4.53,5.18) {task specification};
\draw[humanflow] (12.20,4.52)--(12.20,5.20)--(8.03,5.20)--(8.03,5.79);
\node[small,fill=white,inner sep=2pt,text=ovhuman] at (10.42,5.20) {inspect codes};
\end{tikzpicture}%
""".replace("__CELLS__", "\n".join(cells))
    content = content.replace("__WITNESS_COUNT__", str(witness_count))
    content = content.replace("__REFUTATION_COUNT__", str(len(refutations)))
    (args.out_dir / "fig_overview_content.tex").write_text(content)
    (args.out_dir / "fig_overview.tex").write_text(r"""% GENERATED by scripts/make_pipeline_overview.py.
\begin{figure}[H]
\centering
\resizebox{\linewidth}{!}{\input{fig_overview_content}}
\caption{The researcher-in-the-loop discovery pipeline.}
\label{fig:overview}
\end{figure}
""")
    if args.standalone:
        (args.out_dir / "fig_overview_standalone.tex").write_text(r"""\documentclass[border=1pt]{standalone}
\usepackage[T1]{fontenc}
\usepackage{times,amsmath,amssymb,tikz,xcolor,graphicx}
\usetikzlibrary{arrows.meta,calc}
\begin{document}
\noindent\input{fig_overview_content}
\end{document}
""")
    print(f"Vector overview -> {args.out_dir}")


if __name__ == "__main__":
    main()
