"""Export verbatim Theorem 1 goal/proof excerpts for the paper appendix."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'formal/eaqecc/CodingTheoryLib/Research/ICLR2027EAQECC'
PAPER = ROOT / 'paper/iclr2027/paper'


def main():
    solution = (SOURCE / 'Comparator/Theorem1Solution.lean').read_text()
    goal = solution[solution.index('theorem theorem1_exact_goal'):solution.index('#print axioms')].strip()
    proof = (SOURCE / 'Theorem1.lean').read_text()
    theorem = proof[proof.index('theorem theorem1_exact {'):proof.index('#print axioms theorem1_closed_form')]
    body = theorem.split(':= by', 1)[1].strip('\n')
    for name, code in [('goal', goal), ('solution', body)]:
        glyphs = {'𝔽': r'\mathbb{F}', 'ℕ': r'\mathbb{N}',
                  '₂': r'{}_2', 'δ': r'\delta', '≤': r'\le',
                  '∨': r'\lor', '∃': r'\exists', '≠': r'\ne',
                  '∧': r'\land', '⟨': r'\langle', '⟩': r'\rangle',
                  '·': r'\cdot'}
        code = ''.join('(*@$' + glyphs[c] + '$@*)' if c in glyphs else c for c in code)
        if any(ord(c) > 127 for c in code):
            raise ValueError('An unmapped Lean glyph would be missing in the PDF')
        (PAPER / f'lean_theorem1_{name}.tex').write_text(
            '% Verbatim excerpt generated by scripts/make_lean_excerpt.py.\n'
            + '\\begin{lstlisting}[style=leancode]\n' + code.rstrip() + '\n\\end{lstlisting}\n')


if __name__ == '__main__':
    main()
